
#define TTMDEV_MAGIC 0xEA

#define TTMDEV_NAME "ttmdev"

#define TTMDEV_GET_WAKEUP _IO(TTMDEV_MAGIC, 0x01)
#define TTMDEV_PULSE_RESET _IO(TTMDEV_MAGIC, 0x02)
#define TTMDEV_SET_POLARITY_RISING _IO(TTMDEV_MAGIC, 0x03)
#define TTMDEV_SET_POLARITY_HIGH _IO(TTMDEV_MAGIC, 0x05)
#define TTMDEV_GET_POLARITY _IO(TTMDEV_MAGIC, 0x07)
#define TTMDEV_RECOVERY _IO(TTMDEV_MAGIC, 0x08)
#define TTMDEV_USE_ESE _IOW(TTMDEV_MAGIC, 0x09, unsigned int)


#define TTMDEV_LEGACY_GET_WAKEUP _IOR(TTMDEV_MAGIC, 0x01, unsigned int)
#define TTMDEV_LEGACY_PULSE_RESET _IOR(TTMDEV_MAGIC, 0x02, unsigned int)
#define TTMDEV_LEGACY_SET_POLARITY_RISING \
	_IOR(TTMDEV_MAGIC, 0x03, unsigned int)
#define TTMDEV_LEGACY_SET_POLARITY_HIGH _IOR(TTMDEV_MAGIC, 0x05, unsigned int)
#define TTMDEV_LEGACY_GET_POLARITY _IOR(TTMDEV_MAGIC, 0x07, unsigned int)
#define TTMDEV_LEGACY_RECOVERY _IOR(TTMDEV_MAGIC, 0x08, unsigned int)

#define ACCESS_OK(x, y, z) access_ok(x, y, z)

