#prize-add prize-wangyunqing-20181110-start
obj-$(CONFIG_PRIZE_HARDWARE_INFO) += hardware_info/
#prize-add prize-wangyunqing-20181110-end

#/*prize add by zhuzhengjiang for camera ldo wl2868c 20220309  start*/
obj-$(CONFIG_PRIZE_CAMERA_LDO_WL2868C) += wl2868c/
#/*prize add by zhuzhengjiang for camera ldo wl2868c 20220309  end*/
